# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: 
  image: 'rocker/r-base:3.6.0'

steps:
- script: Rscript -e 'R.version'
  displayName: 'Confirm R version'

- script: Rscript -e 'print("hello world")'
  displayName: 'Run R expression'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
